name: partywitty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Common dependencies
  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  dev_bloc_cli: ^0.0.7
  equatable: ^2.0.7
  intl: ^0.20.2
  video_player: ^2.10.1
  flutter_image_slideshow: ^0.1.6
  blur: ^4.0.2
  # Google Fonts
  google_fonts: ^6.3.2
  dio: ^5.9.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/

  # Fonts (optional if you want to use local Lexend)
  fonts:
    - family: 'Lexend'
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
